# Generated by Django 3.1.7 on 2021-06-20 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210617_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ceatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
